"""initial_schema

Revision ID: b73e2d4a0fd2
Revises: 
Create Date: 2026-07-06 18:13:09.262032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b73e2d4a0fd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_hashtag_trends',
    sa.Column('hashtag', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('category_label', sa.String(length=100), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('growth_percentage', sa.Float(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktok_hashtag_trends_category'), 'tiktok_hashtag_trends', ['category'], unique=False)
    op.create_index(op.f('ix_tiktok_hashtag_trends_hashtag'), 'tiktok_hashtag_trends', ['hashtag'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('beauty_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skin_subtone', sa.String(length=20), nullable=True),
    sa.Column('skin_subtone_confidence', sa.Float(), nullable=True),
    sa.Column('skin_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hair_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hand_morphology', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brow_visajismo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trend_affinity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evolution_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beauty_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beauty_profiles_skin_subtone', 'beauty_profiles', ['skin_subtone'], unique=False)
    op.create_index(op.f('ix_beauty_profiles_user_id'), 'beauty_profiles', ['user_id'], unique=True)
    op.create_table('biometric_consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('consent_type', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_text_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('legal_framework', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_consents_user_id'), 'biometric_consents', ['user_id'], unique=False)
    op.create_index('uq_active_consent_type_version', 'biometric_consents', ['user_id', 'consent_type', 'version'], unique=True, postgresql_where='revoked_at IS NULL')
    op.create_table('beauty_scan_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('beauty_profile_id', sa.UUID(), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beauty_profile_id'], ['beauty_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beauty_scan_sessions_user_id'), 'beauty_scan_sessions', ['user_id'], unique=False)
    op.create_table('evolution_snapshots',
    sa.Column('beauty_profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('beauty_score', sa.Integer(), nullable=False),
    sa.Column('skin_concerns_count', sa.Integer(), nullable=False),
    sa.Column('hair_damage_level', sa.String(length=20), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beauty_profile_id'], ['beauty_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_snapshots_beauty_profile_id'), 'evolution_snapshots', ['beauty_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evolution_snapshots_beauty_profile_id'), table_name='evolution_snapshots')
    op.drop_table('evolution_snapshots')
    op.drop_index(op.f('ix_beauty_scan_sessions_user_id'), table_name='beauty_scan_sessions')
    op.drop_table('beauty_scan_sessions')
    op.drop_index('uq_active_consent_type_version', table_name='biometric_consents', postgresql_where='revoked_at IS NULL')
    op.drop_index(op.f('ix_biometric_consents_user_id'), table_name='biometric_consents')
    op.drop_table('biometric_consents')
    op.drop_index(op.f('ix_beauty_profiles_user_id'), table_name='beauty_profiles')
    op.drop_index('ix_beauty_profiles_skin_subtone', table_name='beauty_profiles')
    op.drop_table('beauty_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiktok_hashtag_trends_hashtag'), table_name='tiktok_hashtag_trends')
    op.drop_index(op.f('ix_tiktok_hashtag_trends_category'), table_name='tiktok_hashtag_trends')
    op.drop_table('tiktok_hashtag_trends')
    # ### end Alembic commands ###
